### ISSUE TITLE
Investigate Interaction Types for Guide To Pharmacology

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#112]
G2P interaction types [should be imported](https://github.com/genome/dgi-db/blob/master/lib/genome/importers/guide_to_pharmacology_interactions/guide_to_pharmacology_interactions_tsv_importer.rb#L26), but for some reason are not. Perhaps this has to do with the [string parsing](https://github.com/genome/dgi-db/blob/master/lib/genome/importers/guide_to_pharmacology_interactions/guide_to_pharmacology_interactions_row.rb#L31) in the row_importer file? @acoffman, could you and @gspies look at this one together?

**Comment by gspies** [comment]
@ahwagner, this is the data file I used for the G2P import: https://gist.github.com/gspies/1136da973e65071ed83b797269f884b0#file-int-tsv

I did not make any changes to the code.The output for the import is below (I think this shows it was imported successfully)
"Starting import!
Skipping presumed header line in /home/greg/Downloads/int.tsv...
Imported 1577 gene_claims.
Imported 4886 gene_claim_aliases.
Imported 0 gene_claim_attributes.
Imported 0 gene_gene_interaction_claims.
Imported 0 gene_gene_interaction_claim_attributes.
Imported 0 gene_claim_categories_gene_claims.
Imported 6195 drug_claims.
Imported 12597 drug_claim_aliases.
Imported 396 drug_claim_attributes.
Imported 12854 interaction_claims.
Imported 48597 interaction_claim_attributes.
Clearing cache
Done."

**Comment by ahwagner** [comment]
Yeah, these records are clearly imported, but part of the record (the interaction type) is recorded incorrectly. For example, [row 1916](https://gist.github.com/gspies/1136da973e65071ed83b797269f884b0#file-int-tsv-L1916) has a type of "Inhibitor", which is an allowable type (see [here](https://github.com/genome/dgi-db/blob/master/lib/genome/importers/guide_to_pharmacology_interactions/guide_to_pharmacology_interactions_row.rb#L14-L15)). Yet, in the [corresponding claim](http://dgidb.genome.wustl.edu/interaction_claims/cad699ee-4af7-452b-b86d-0e9a14180549), it has a recorded interaction type of "N/A". This will require some debugging during the import process to see where the problem lies. @gspies, let me know if this needs clarification, and let me or @acoffman know if you get stuck along the way.

**Comment by kcotto** [comment]
It looks as though N/As are assigned to interaction claims in the importer. I believe that editing a few lines, including adding the attribute `interaction_type` should fix this bug.

**Comment by kcotto** [comment]
After further investigation, I noticed that there is a line missing that calls the `attribute :interaction_type` 

This will be fixed in the new updated version.

**Comment by kcotto** [comment]
I believe this was fixed in #264. Can you verify @susannasiebert?

**Comment by susannasiebert** [comment]
Yes, this was fixed.
