### ISSUE TITLE
New definition of druggable genome

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#118]
From preprint [The druggable genome and support for target identification and validation in drug development](http://www.biorxiv.org/content/early/2016/07/26/066027).

Add this list of genes to the `Druggable Genome` category.

**Comment by ahwagner** [comment]
Now in STM: http://stm.sciencemag.org/content/9/383/eaag1166

**Comment by kcotto** [comment]
Importer has been written. Import appears to succeed but the source is not included into the database (addressed in new issue #175)

**Comment by kcotto** [comment]
This was completed with PR #182. I recommend this issue to be closed @ahwagner

**Comment by ahwagner** [comment]
agreed.
