### ISSUE TITLE
Investigate moving deployment of dgidb to the cloud

### ISSUE THREAD

**Issue by malachig** [griffithlab/dgi-db#119]
This would allow us to have more control over site updates, and that in turn would help us turn on auto-updating of some content sources.  Current updates require a 45 minute outage.

**Comment by ahwagner** [comment]
This should be mitigated somewhat by #148.

**Comment by ahwagner** [comment]
@obigriffith @malachig, do we still want to look into this? Costs should certainly be part of this discussion

**Comment by obigriffith** [comment]
I guess the big question is how critical this currently is.

**Comment by ahwagner** [comment]
Perhaps it's entirely unnecessary, with sufficient modification to our puppet deploy process and DGIdb background tasks. @susannasiebert is working on live auto-updating (from the production environment, see #148), and @acoffman and I could probably work out a faster way of deploying DGIdb, or at least providing friendlier responses while it's updating.
