### ISSUE TITLE
update importer documentation

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#120]
Writing importers should be easy.

See existing documentation: https://github.com/genome/dgi-db/blob/master/files/WritingANewImporter.pdf

and update it.

**Comment by acoffman** [comment]
Link to some also outdated confluence docs: https://confluence.gsc.wustl.edu/display/BIO/DGIdb

**Comment by kcotto** [comment]
Instead of a static document within the repo, I've created a wiki page (https://github.com/griffithlab/dgi-db/wiki/Importing-a-new-source-into-DGIdb). This will allow for easier editing and updating in the future.

**Comment by acoffman** [comment]
Nice work! Closing!
