### ISSUE TITLE
roll up drug attributes and aliases into drug group

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#122]
see `drugs` table

**Comment by susannasiebert** [comment]
It loos like all `drug_claims` only have one entry in the `drug_claims_drugs` bridge table. Any objection to moving the `drug_claims_drugs.drug_id` foreign key straight onto the `drug_claims` table? This would eliminate the drug_claims_durgs bridge table.

```
select * from (select drug_claims.id, count(drug_claims_drugs.drug_id) as count from drug_claims, drug_claims_drugs where drug_claims.id = drug_claims_drugs.drug_claim_id  group by drug_claims.id order by count desc) as drug_count where count > 1;
 id | count 
----+-------
(0 rows)
```

**Comment by ahwagner** [comment]
I'm all for fewer tables, and agree that the bridge table is unnecessary here (by design, any claim can only belong to one group... true for genes and drugs). My only concern, however, is that this messes with Rails conventions. @acoffman could probably shed some light on how easy it would be to make this change.

**Comment by acoffman** [comment]
The only reason to have the bridge table would be to support a many-to-many relationship. If we don't anticipate a claim ever belonging to more than one group (which I agree - I don't think we do); I'm all for getting rid of it. Its a "big" change in the sense that we'll probably have to change a ton of small things, but functionally, its pretty minor and shouldn't be a big deal.

**Comment by susannasiebert** [comment]
I also checked on `gene_claims_genes` and the same hold true there:
```

**Comment by acoffman** [comment]
Awesome! So for starters, we're going to want to add a `gene_id` to `gene_claims` (likewise with drugs, and eventually interactions), move the data from the bridge tables to the new foreign key, and finally remove the bridge tables altogether. 

We'll have to change some of the presentation logic, the way the groupers work, and probably some of the queries as well. But it should dramatically simplify things ultimately.

**Comment by susannasiebert** [comment]
Not sure if that is something we would want to address but there are 6017 `drug_claims` that do not have a link in `drug_claims_drugs`. Likewise, there are 25507 `gene_claims` that do not a link in `gene_claims_genes`.

```
select count(*) from drug_claims full outer join drug_claims_drugs on drug_claims.id = drug_claims_drugs.drug_claim_id where drug_claims_drugs.drug_id is null;
 count 
-------
  6017
(1 row)
```

```
select count(*) from gene_claims full outer join gene_claims_genes on gene_claims.id = gene_claims_genes.gene_claim_id where gene_claims_genes.gene_id is null;
 count 
-------
 25507
(1 row)
```

**Comment by acoffman** [comment]
So that's unfortunate but accurate. Basically the "groupers" don't manage to definitively group each claim into a larger entity, so there definitely are "orphaned" claims so to speak.

This is reflected on the [sources](http://dgidb.genome.wustl.edu/sources) where you can see the total claim count, and then the number that were successfully grouped for each individual source.

Improvements to the grouping algorithms might help those numbers, but at the moment its a known/expected situation.

**Comment by susannasiebert** [comment]
There are currently 42 `interaction_claims` that have multiple `interaction_claim_types`. How should we roll these up into `interactions`. Should an interaction be able to have multiple interaction_types? Or would we want to roll them up into one somehow? I have attached the table of the interaction_claims in question

```

**Comment by susannasiebert** [comment]
On `interaction_claims` there is also still a column `interaction_type` that is currently always empty and probably just a holdover from an old version of the schema. Is it save to remove that column?

**Comment by susannasiebert** [comment]
I believe this is all done. I'm resolving this issue.
