### ISSUE TITLE
Review sources for additional metadata

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#132]
We should start by examining our CIViC importer, but also look through our other importers for metadata that might have been missed/added since the original importers were written.

**Comment by nspies13** [comment]
FDA-approved targeted therapies should be a high priority import. Intense reformatting will be need for this list, but I think it'll be worth the time. 

https://www.mycancergenome.org/content/molecular-medicine/overview-of-targeted-therapies-for-cancer/

**Comment by ahwagner** [comment]
mycancergenome update has been moved to it's own issue, #155. This issue will remain as a discussion for additional sources to review.

**Comment by ahwagner** [comment]
CIViC and DoCM will be reviewed in #78.
