### ISSUE TITLE
Normalize interaction_claim_attributes

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/dgi-db#137]
The PubMed ID in the interaction_claim_attributes table is currently stored with one of two names: `PMID` or `PubMed ID for Interaction`. I propose to either decide on one of those two names or even denormalize this attribute into its own table.

There are currently attributes with name `Direct Interaction` and `Direct Interaction?`. I propose that we decide on one of these two names and clean up the data.

**Comment by ahwagner** [comment]
@yanyangfeng will be reviewing the attribute fields and normalizing them for import into a PMID model.

**Comment by yanyangfeng** [comment]
I believe this can be closed.
