### ISSUE TITLE
Multiple Linkouts

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#14]
Support linkout url option for each attribute from a source, not just the base URL for drugs.

**Comment by malachig** [comment]
This is a good idea @ahwagner.  Out of curiosity is there a specific example you were thinking of when you opened this issue?

**Comment by ahwagner** [comment]
@malachig when viewing a [gene record](http://dgidb.genome.wustl.edu/genes/AQP9) on DGIdb, the metadata would appear something like the database links section for [ligand results](http://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=7882) on the guide to pharmacology site.

**Comment by malachig** [comment]
Yeah, that sound awesome.  More linking back to the original sources would be great.

**Comment by ahwagner** [comment]
This should be part of #124.

**Comment by ahwagner** [comment]
#165 addresses this partially. However, in cases where there is a huge list of linkouts, it currently eats up too much space. We should link directly to the _claims_ tab if the linkouts take more than one line.
