### ISSUE TITLE
Expose Drug, Gene, Interaction metadata through API

### ISSUE THREAD

**Issue by stuppie** [griffithlab/dgi-db#141]
Is there any way to retrieve identifiers through the API for the biological entities in the response? The **interactions** endpoint only returns a `drugName` field, but no identifiers, such as CAS, Drugbank, or Pubchem IDs. 

It looks like these are present in the [database dump](http://dgidb.genome.wustl.edu/downloads) for drugs from at least several of the data sources. I understand data sources often do not provide this information.

Also, I'm wondering if you all have attempted to normalize drugs when a data source does not provide sufficient identifiers. For example, mycancergenome only provides drug names. If a drug is in both mycancergenome and another source, is it treated as two separate entities?

Thanks in advance

**Comment by ahwagner** [comment]
Hey @stuppie. Thanks for the feedback. We've been making some big changes recently in preparation for our v3.0 launch, and among them we're restructuring how we serve up interaction results.

We agree that this information should be accessible via the API, and our plan is to incorporate the appropriate endpoints and documentation to do so once we've finished refactoring the web side. Watch here for progress.

**Comment by ahwagner** [comment]
@stuppie, I should also mention that we do normalize drug and gene concepts, as described in the [original paper](http://www.nature.com/nmeth/journal/v10/n12/full/nmeth.2689.html) (there called _drug groups_ and _gene groups_, repectively).

**Comment by ahwagner** [comment]
We should create a services_v2 that is centered around the new interaction group, and exposes more of the content of DGIdb.

**Comment by mbrush** [comment]
Hi.  It would also be nice if the API provided IDs of supporting publications for each interaction.  Currently I only see the source database - but not the pubs referenced by each.

**Comment by ahwagner** [comment]
Thanks for the feedback, @mbrush. This is absolutely part of our effort to expose the metadata from the various resources we've assembled. We're prioritizing literature extraction (as available) from our new and existing resources as part of our upcoming 3.0 update.
