### ISSUE TITLE
Query by drug, retrieve interacting genes

### ISSUE THREAD

**Issue by stuppie** [griffithlab/dgi-db#142]
I can get interacting drugs given a gene, but can I do the reverse? I see I can do this from the [main website](http://dgidb.genome.wustl.edu).

**Comment by ahwagner** [comment]
Thanks for the feedback. You absolutely should be able to, but currently no! This should be addressed ASAP--I'll make the changes and push this live today or tomorrow.

**Comment by ahwagner** [comment]
Fix for this issue will be pushed live once #143 is resolved.

**Comment by stuppie** [comment]
Thanks @ahwagner . Can you explain how to use the drug search endpoint? No matter what I try on the http://dgidb.genome.wustl.edu/api/v1/interactions.json endpoint, I always get "You must enter at least one gene name to search!"

**Comment by ahwagner** [comment]
Hey @stuppie. We're going to put documentation out describing the revised API (see #147), but the code that's present in this repo has not yet been pushed live. This is for reasons relating to downtime when we push updates.

We're planning to make it easier to start up a private repo of DGIdb that will be current with this repo, and I'll be putting together an Amazon AMI of our current master branch that you can spin up to use the drug API that's been added here. I've created an issue to track progress on the AMI: #160.

If you want a more immediate solution, you may follow the install instructions for [Linux](https://github.com/griffithlab/dgi-db/blob/master/INSTALL-LINUX) or [OSX](https://github.com/griffithlab/dgi-db/blob/master/INSTALL-OSX) to run a local instance of DGIdb that will have all of the up-to-date changes, including the drug API.

**Comment by ahwagner** [comment]
@stuppie the AMI is now live. Feel free to spin up your own instance of DGIdb following the directions outlined [here](https://github.com/griffithlab/dgi-db/wiki/Using-the-Amazon-AMI). After doing so, you should be able to do drug queries similar to gene queries:

`http://dgidb.genome.wustl.edu/api/v1/interactions.json?drugs=<LIST_OF_DRUG_NAMES>`

**Comment by ahwagner** [comment]
documentation added: https://github.com/griffithlab/dgi-db/pull/200/commits/48e9770f081553e40e34f9389e0a0b9723694e38
