### ISSUE TITLE
Online updating of resources

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#148]
Currently we update DGIdb by running tasks to download / construct TSVs from various sources and then import from those TSVs. We should move all of our updating to online processes (run by production server), and remove the outdated _table drop -> reimport -> regroup_ method to something that can make small changes to the live, production database.

**Comment by acoffman** [comment]
Some notes/tasks from talking to @susannasiebert today.


- [ ] Introduce background processing (likely delayed_job) for online updates
- [ ] Import all of Entrez (and keep it up-to-date) as the basis for Genes (improve grouper performance)
- [ ] Change groupers to operate incrementally instead of dropping and re-doing all groups

Unlike Entrez, we will not import all of PubChem, we will continue to only import entries from PubChem that somehow match a Drug Claim already in the system.

"Updaters" and "Groupers" will be combined into a single step that runs in the background (though each part will still be able to run independently).

Interaction grouper will remain largely unchanged, but gene and drug groupers will be mostly rewritten to build groups for all gene/drug concepts.

**Comment by ahwagner** [comment]
We should consider using a source that has good coverage for immunotherapy and small molecule drugs (Pubchem lacks immuntherapies)

**Comment by susannasiebert** [comment]
We currently have 753 drugs with ChEMBL drug claims in the database:
```
> chembl_drugs = DataModel::DrugClaim.where(nomenclature: 'ChEMBL Drug Identifier').map{|c| c.drug}.compact.uniq
> chembl_drugs.count
=> 753
```
All of them also have drug claims from pubchem:
```
> pubchem_drugs = DataModel::DrugClaim.where(nomenclature: 'pubchem').map{|c| c.drug}.compact.uniq
> (chembl_drugs-pubchem_drugs).count
=> 0
```
We currently have 14828 drugs in the database that do not have any drug claims from pubchem: 
```
> all_drugs = DataModel::Drug.all
> (all_drugs-pubchem_drugs).count
=> 14828
```
None of these have any recorded interactions so we could delete them:
```
> nonpubchem_drugs = all_drugs-pubchem_drugs
> nonpubchem_drugs.map{|d| d.interactions}.compact.flat_map{|i| i}.count
=> 0
```

**Comment by susannasiebert** [comment]
Gene Grouping:
1. Iteratively on interaction source update:
1.a. Group new gene claims with existing groups
2. Iteratively on gene source updates: 
2.a. Group new genes with ungrouped gene claims
2.b. Re-group gene claims with removed genes
3. This time - regroup all:
3.a. See how many orphaned claims we still have

**Comment by susannasiebert** [comment]
I deleted all existing genes from my local database and reran the gene grouper. 

There are almost 28k orphaned drug claims:
```
dgidb=# select count(*) from gene_claims where gene_id is null;
 count 
-------
 27844
(1 row)
```

These are their sources:
```
dgidb=# select source_db_name, count(distinct gene_claims.id) from gene_claims join sources on sources.id = gene_claims.source_id where gene_id is null group by source_db_name;
         source_db_name          | count 
---------------------------------+-------
 BaderLabGenes                   |     2
 CarisMolecularIntelligence      |     9
 ChEMBL                          |    15
 DrugBank                        |    60
 Ensembl                         | 25497
 Entrez                          |     1
 GO                              |   899
 GuideToPharmacologyGenes        |    39
 GuideToPharmacologyInteractions |    65
 HopkinsGroom                    |    60
 MyCancerGenome                  |     1
 MyCancerGenomeClinicalTrial     |     2
 PharmGKB                        |    21
 RussLampel                      |   554
 TEND                            |    15
 TTD                             |   505
 TdgClinicalTrial                |    28
 dGene                           |    71
(18 rows)
```

Only 712 of them have a associated interaction claim:
```
dgidb=# select count(distinct gene_claims.id) from gene_claims join interaction_claims on interaction_claims.gene_claim_id = gene_claims.id where gene_id is null;
 count 
-------
   712
(1 row)
```

For the gene claims that do have interaction claims, here are the sources of the gene claims:
```
dgidb=# select source_db_name, count(distinct gene_claims.id) from gene_claims join interaction_claims on interaction_claims.gene_claim_id = gene_claims.id join sources on sources.id = gene_claims.source_id where gene_id is null group by source_db_name;
         source_db_name          | count 
---------------------------------+-------
 ChEMBL                          |    15
 DrugBank                        |    60
 GuideToPharmacologyInteractions |    65
 MyCancerGenome                  |     1
 MyCancerGenomeClinicalTrial     |     2
 PharmGKB                        |    21
 TEND                            |    15
 TTD                             |   505
 TdgClinicalTrial                |    28
(9 rows)
```

**Comment by ahwagner** [comment]
Hrm. The lack of mapping between Entrez and Ensembl is a little concerning, and my guess is that this is leading to failed grouping of some of the downstream resources. @susannasiebert, looking at the underlying records for Ensembl, is there an outdated (or missing) link to our most recent Entrez gene list?

**Comment by ahwagner** [comment]
It appears that the grouping for Ensembl is part of the gene grouper, and treated no differently than other sources. These Ensembl gene claims have Ensembl IDs as part of the record (e.g. ENSG00000351), which groups with aliases from Entrez gene claims. However, it appears that of the ~59K Entrez gene claims, only 26695 have Ensembl ID aliases associated with them. We should identify a more complete mapping, if such a resource exists.

**Comment by ahwagner** [comment]
For drug grouping, a ChEMBL "downloader" exists (and could use updating) [here](https://github.com/griffithlab/dgi-db/blob/master/lib/genome/downloaders/chembl.py). A newer version of ChEMBL's database is available [here](ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/releases/chembl_23/).

Initial investigation (spot-checking) suggests that ChEMBL may be a better starting point than PubChem for drugs, unless PubChem SIDs are included (enormous).

**Comment by ahwagner** [comment]
@kcotto should provide us with a list of sources from her review (https://docs.google.com/spreadsheets/d/1lbFwyQj6wOvlK145hj0lcnWGkwuL210Qyx1K_T9yzJM/edit#gid=0) that are updated frequently enough and have a mechanism (data dump/API) for online updating.

**Comment by kcotto** [comment]
Sources to be updated frequently with links to data download/API page are below. If there is anything I can do to help with the import of these sources, please let me know. I will continue to work on importers for the more static sources.

- Guide to Pharmacology: http://www.guidetopharmacology.org/download.jsp
- GO: http://www.geneontology.org/page/downloads
- My Cancer Genome: https://www.mycancergenome.org/about/api-licensing/ (need to contact them about the API)
PharmGKB: https://www.pharmgkb.org/downloads/ (need to make sure our license is still valid)
CIViC: https://genome.github.io/civic-api-docs/
DoCM:
DrugBank: https://www.drugbank.ca/releases/latestch
ChEMBL: https://www.ebi.ac.uk/chembl/downloadsent
Entrez: ftp://ftp.ncbi.nih.gov/gene/DATA/GENE_INFO/Mammalia/
Ensembl: http://www.ensembl.org/info/data/ftp/index.html
PubChem: ftp://ftp.ncbi.nlm.nih.gov/pubchem/

**Comment by acoffman** [comment]
Progress:
   - [ ] Guide to Pharmacology
   - [ ]  GO
   - [ ]  My Cancer Genome
    - [ ] PharmGKB
   - [ ]  CIViC
   - [ ]  DoCM
    - [ ] DrugBank
   - [ ]  ChEMBL
    - [ ] Entrez
   - [ ]  Ensembl
    - [ ] PubChem

**Comment by ahwagner** [comment]
In updating Guide to Pharmacology, we should ensure #112 is addressed.

**Comment by susannasiebert** [comment]
For DrugBank, it looks like you need to sign up before being able to download the file. I haven't been able to find a direct ULR for downloading their data. @kcotto were you able to find a way to download their data without signing up?

**Comment by kcotto** [comment]
@susannasiebert It looks like they have an open dataset (https://www.drugbank.ca/releases/latest#open-data) which just lists DrugBankID, Common Name, CAS, UNII, Synonyms, and Standard InChI Key but only for a little over 13,000 compounds. 

It seems that in order to get what we want, an account would need to be created.

**Comment by kcotto** [comment]
Looking at the MyCancerGenome API, I'm not sure that it would actually be useful for us. I recommend removing it from automatic updating and just manually updating from the webpages every so often.

**Comment by ahwagner** [comment]
Re https://github.com/griffithlab/dgi-db/issues/148#issuecomment-308455652, we will need an account to access DrugBank's data file, and we can download it programatically:

```ruby
request = Net::HTTP::Get.new(uri.request_uri)
request.basic_auth("username", "password")
```

This will require a username and password we specify in ENV or a private .yml file. I have account credentials we can use for the username and password.

**Comment by ahwagner** [comment]
@susannasiebert and @kcotto: work together to see if you can incorporate @kcotto's revised DrugBank updater into an online updater.

**Comment by kcotto** [comment]
All of these have been updated except PharmGKB, for which the status of our license is still ambiguous.

**Comment by ahwagner** [comment]
let's start running these routinely, and use that to address #177.

**Comment by kcotto** [comment]
PharmGKB has been merged into staging so I think we can close this?

**Comment by susannasiebert** [comment]
Yes, let's close this. There is some additional work we need to do to handle the data updates that are now are getting created on production (i.e. get rid of the static data.sql commits) but that can be tracked in a new issue.
