### ISSUE TITLE
Update contacts page

### ISSUE THREAD

**Issue by malachig** [griffithlab/dgi-db#151]
It really is quite out of date.  1/2 people there are no longer working at MGI.  Others would deserve credit are probably missing.  Maybe move people that are gone to the "additional conceptual contributors" section and have a separate list for the current team.

Also we currently have almost no MGI or WASHU branding anywhere on the site.  This is an unfortunate oversight.  Would be good to add that to the footer as we have on CIViC and other projects.

**Comment by ahwagner** [comment]
This has been updated (twice: c148060, 48ce3d5), but never pushed live. It's due for another update, though, and I like the idea of branching off previous contributors to a new well.
