### ISSUE TITLE
add WUSTL and MGI branding to site

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#152]
from #151

**Comment by yanyangfeng** [comment]
@malachig, @ahwagner, was there anything I needed to do to make sure this branding stuff wouldn't piss any admin off?

**Comment by malachig** [comment]
Can you post a screenshot for reference?

**Comment by yanyangfeng** [comment]
![screen shot 2017-08-25 at 1 40 49 pm](https://user-images.githubusercontent.com/16638655/29727855-37e16708-899b-11e7-8152-ce8992e37d01.png)

**Comment by malachig** [comment]
This looks fine to me.
