### ISSUE TITLE
update mycancergenome

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#155]
From @nspies13 comment in #132: https://github.com/griffithlab/dgi-db/issues/132#issuecomment-293364837

**Comment by ahwagner** [comment]
Review PR #156

**Comment by ahwagner** [comment]
@kcotto, please merge the information from the two pages specified in https://github.com/griffithlab/dgi-db/pull/156#pullrequestreview-43013740, and merge the results into the original MyCancerGenome importer.

**Comment by kcotto** [comment]
PR #156 updated to combine this My Cancer Genome page and another that contain overlapping information.

**Comment by kcotto** [comment]
Fixed with PR #156 which has been merged into master.
