### ISSUE TITLE
Place database constraints to ensure unique entries in various tables

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/dgi-db#168]

**Comment by susannasiebert** [comment]
Suggested constraints:
- `drug_aliases`: (`drug_id`, `alias`, `nomenclature`)
- `drug_attributes`: (`drug_id`, `name`) OR (`drug_id`, `name`, `value`) depending on whether we want to allow different values for the same attribute name
- `drug_claim_aliases`: (`drug_claim_id`, `alias`, `nomenclature`)
- `drug_claim_attributes`: (`drug_claim_id`, `name`) OR (`drug_claim_id`, `name`, `value`) depending on whether we want to allow different values for the same attribute name
- `drug_claims`: (`name`, `nomenclature`, `source_id`)
- `drugs`: (`name`)
- `gene_aliases`: (`gene_id`, `alias`, `nomenclature`)
- `gene_attributes`: (`gene_id`, `name`) OR (`gene_id`, `name`, `value`) depending on whether we want to allow different values for the same attribute name
- `gene_claim_aliases`: (`gene_claim_id`, `alias`, `nomenclature`)
- `gene_claim_attributes`: (`gene_claim_id`, `name`) OR (`gene_claim_id`, `name`, `value`) depending on whether we want to allow different values for the same attribute name
- `gene_claims`: (`name`, `nomenclature`, `source_id`)
- `genes`: (`name`)
- `interaction_attributes`: (`interaction_id`, `name`) OR (`interaction_id`, `name`, `value`) depending on whether we want to allow different values for the same attribute name
- `interaction_claim_attributes`: (`interaction_claim_id`, `name`) OR (`gene_claim_id`, `name`, `value`) depending on whether we want to allow different values for the same attribute name
- `interaction_claims`: (`drug_claim_id`, `gene_claim_id`, `source_id`)
- `interactions`: (`drug_id`, `gene_id`)

**Comment by susannasiebert** [comment]
@ahwagner Can you please review the list of suggested constraints at your convenience? There are a couple where there are two options that we need to make a decision on.

**Comment by susannasiebert** [comment]
I've been going through the list and comparing the number of unique entries with the constraints listed above to the number of total entries. For the most part these matched up, meaning there were no duplicates. Here are the exceptions:
- We have about 2000 duplicate drug claims:
```
dgidb=# select count(*) from drug_claims;
 count 
-------
 33413
(1 row)
dgidb=# select count(distinct(name, nomenclature, source_id)) from drug_claims;
 count 
-------
 31367
(1 row)
```
- We have about 3500 duplicate interaction claims:
```
dgidb=# select count(*) from interaction_claims;
 count 
-------
 40129
(1 row)

dgidb=# select count(distinct(drug_claim_id, gene_claim_id, source_id)) from interaction_claims;
 count 
-------
 36590
(1 row)
```
- There are almost 20000 duplicate interactions pointing to a bug in the interaction grouper, which I will investigate as part of this issue:
```
dgidb=# select count(*) from interactions;
 count 
-------
 37548
(1 row)

dgidb=# select count(distinct(drug_id, gene_id)) from interactions;
 count 
-------
 18774
(1 row)
```

**Comment by susannasiebert** [comment]
I changed some stuff in the interaction grouper and reran it after deleting all interactions. I now get the expected number of interactions.

**Comment by ahwagner** [comment]
- drug_aliases: (drug_id, UPPER(alias))
  - We should revise our rollup strategy to keep only the most frequent and specific (i.e. not "Drug Synonym(s)") nomenclature for a given alias.
- drug_attributes: (drug_id, name, value)
- drug_claim_aliases: (drug_claim_id, alias, nomenclature)
- drug_claim_attributes: (drug_claim_id, name, value)
- drug_claims: (name, nomenclature, source_id)
- drugs: (name)
- gene_aliases: (gene_id, UPPER(alias))
  - We should revise our rollup strategy to keep only the most frequent and specific (i.e. not "Gene Synonym(s)") nomenclature for a given alias.
- gene_attributes: (gene_id, name, value) 
- gene_claim_aliases: (gene_claim_id, alias, nomenclature)
- gene_claim_attributes: (gene_claim_id, name, value)
- gene_claims: (name, nomenclature, source_id)
- genes: (name)
- interaction_attributes: (interaction_id, name, value) 
- interaction_claim_attributes: (interaction_claim_id, name, value) 
- interaction_claims: (drug_claim_id, gene_claim_id, source_id)
- interactions: (drug_id, gene_id)

**Comment by susannasiebert** [comment]
Should we maybe then get rid of the nomenclature columns for `drug_aliases` and `gene_aliases` altogether instead of trying to determine the "best" nomenclature?

**Comment by ahwagner** [comment]
yeah, I thought about that, but I like the idea of providing the additional information. A person might wonder about the context of some strings, but if you're told it's a db identifier for a specific resource, that might make more sense. It does increase the curation burden this way, but that's part of the value we're adding as an aggregate resource.

**Comment by susannasiebert** [comment]
Ok, I will try to come up with a standard procedure to determine the "best" nomenclature.

**Comment by susannasiebert** [comment]
The easiest solution to this problem would be to rank the nomenclatures used for gene and drug aliases so that the highest ranked nomenclatures are preferably used for grouping. This could be a simply array in the groupers. Otherwise we run into problems with aliases that are only supported by a "Gene Synonyms" nomenclature or for cases where we have exactly one match for different nomenclatures, e.g., "IRX2" is an alias with the "Ensembl Gene Name" and the "Gene Symbol" nomenclature. In the latter case if we don't rank the available nomenclatures the algorithm would be non-deterministic.

**Comment by susannasiebert** [comment]
I'm currently running the interaction grouper, which is the last thing that needs to happen before I can make a new data dump. I'm not sure that it will finish before I have to leave for the day. I'm planning on working from home for a bit tomorrow to wrap this up and make a PR.
