### ISSUE TITLE
Update search form

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#174]
The search form should be updated.

**Layout:**
- [ ] Condense form to use horizontal whitespace and fit onto page without scrolling
- [ ] Visually delineate search form from background
- [ ] Fix JS issues that prevent drug/gene context switching
- [ ] Allow form expanding to additional filters for "Advanced Search"

**Features:**
_Quick Filters_
- [ ] Clinically actionable genes
- [ ] FDA approved drugs
- [ ] Anti-neoplastic (if possible)
- [ ] Immunotherapies

_Advanced Filters_
- [ ] Consensus searching (interactions with a certain score)

**Comment by yanyangfeng** [comment]
how about 
- druggable genome
- drug resistance

as categories for filtering drug -> gene searches on?

**Comment by ahwagner** [comment]
Bug makes landing page form look bad after merging in rails update: 
<img width="1427" alt="screen shot 2017-06-22 at 4 35 22 pm" src="https://user-images.githubusercontent.com/811065/27457068-e65e266e-5768-11e7-9d2c-8e0b6ca0a304.png">

**Comment by ahwagner** [comment]
Also, info menu is now mostly off-screen:

<img width="185" alt="screen shot 2017-06-22 at 4 37 10 pm" src="https://user-images.githubusercontent.com/811065/27457119-1c414b9e-5769-11e7-98a3-dea9e36813f2.png">
