### ISSUE TITLE
Next update of data sources

### ISSUE THREAD

**Issue by superciccio14** [griffithlab/dgi-db#176]
According to the [page](http://dgidb.genome.wustl.edu/sources) of details of data sources, it has been a long time since the last update. Are you going to perform a major update?

**Comment by ahwagner** [comment]
Hi @superciccio14, thanks for your interest in the Drug Gene Interaction Database.

We are actively working on updating the database schema, frontend, and source content in preparation for a major version release later this month.

You can monitor our progress on this repo (see [graphs](https://github.com/griffithlab/dgi-db/graphs/contributors) for an overview) and test out our latest changes on our [Amazon Machine Image](https://github.com/griffithlab/dgi-db/wiki/Using-the-Amazon-AMI).

**Comment by superciccio14** [comment]
@ahwagner thank you for your reply and excuse me if come back to the question. Can you confirm that the last data version available both on the web site and via API dates back to February of the last year?
