### ISSUE TITLE
Consider implementing a post-grouping cleanup step

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/dgi-db#178]
We should discuss adding a clean-up step after running groupers to delete orphaned claims (claims that could not get grouped). Orphaned claims increase the runtime of the groupers which will impact the automated updating process.

This is related to #148

**Comment by ahwagner** [comment]
In addition, this step should update the counts of grouped and total claims.

This is currently handled by our Genome::Normalizers::PopulateCounters class, but it will need to be revised for the changes made to our model.
