### ISSUE TITLE
Chembl Molecule Pref_name is not unique

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#195]
The Chembl Molecule table has multiple (non-NULL) molecules with the same pref_name. Investigate if there are additional data available in the table that can help select a representative molecule.

Currently these molecules are uniquified and the shared pref_name is added as an alias to each.

**Comment by ahwagner** [comment]
After investigating, this appears to be due (at least in part) to stereoisoforms. A reasonable selector will be to select the molecule with the highest max phase.

e.g. https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1201258/ is the uniquified form of PEMETREXED we have in DGIdb, and has a max phase 0 (research). In contrast, https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL225072/ is also named PEMETREXED, but has max phase 4 (approved). A third (unnamed) stereoisoform of this compound also exists: https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL59843/.

**Comment by susannasiebert** [comment]
The new drug grouper dropped this table so this issue can be closed.
