### ISSUE TITLE
add interaction types and update normalizer

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#202]
Currently many entries in DGIdb are of type 'n/a' (e.g. #112), and many of `value` `interaction type` (see #136). 

These interaction types need to be fixed in their respective issues, and then we should update Interactions to have types and update [the normalizer](https://github.com/griffithlab/dgi-db/blob/master/lib/genome/normalizers/interaction_claim_type.rb) to create/update those types after normalizing the interaction_claims.

**Comment by susannasiebert** [comment]
I think this can be closed.
