### ISSUE TITLE
fix immunotherapy filter

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#206]
Currently immunotherapy filter [looks for anti-neoplastic flag](https://github.com/griffithlab/dgi-db/blob/master/app/filters/immunotherapy.rb#L17). This needs to be fixed.

Also, the definition of `immunotherapy` should be expanded. Currently I'm using antibodies, but we should include _any_ drugs that are immunomodulatory.

I'll scan through the ChEMBL documentation (ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/schema_documentation.html) to see if there's any other field we can use to improve on this.

**Comment by obigriffith** [comment]
I think this filter may be misleading to many users. There are many targeted therapies that take the form of antibodies. Consider trastuzumab - the main mechanism of action is binding to the extracellular domain, preventing HER2 dimerization, and thus inhibiting MAPK, PI3K/AKT pathways. Attracting immune cells is certainly another proposed key mechanism of Trastuzumab. But, in general it is not thought of as an immune therapy in the same way as checkpoint blockade inhibitors, etc. We would need to look into the immunomodulatory category as well. This might include both immune activation and suppression which would also likely include drugs that are not currently/commonly thought of as immune therapies. At least not cancer immune therapies. That may be an important distinction to clarify as well.

**Comment by malachig** [comment]
Yeah if the point here is to limit search to non-small-molecule drugs that are often missing from drug resources (such as PubChem) I think that would be fine.  But probably the `immunotherapy` title could be renamed.  A common assumption when hearing of a filter called `immunotherapy` may be that its mechanism of action involves immunomodulation (checkpoint blockade, cancer vaccines, CAR t-cells, etc., etc.).

**Comment by yanyangfeng** [comment]
Ya I originally was thinking immuno-modulatory drugs - agree that if things like Trastuzumab are included, that could get confusing. I suppose we could just change the name of the filter to "Non-small-molecule" or something if that fits - though I'm not exactly sure what exactly is flagged as immunotherapy in the db right now. I feel like immuno-modulatory is more interesting though.
