### ISSUE TITLE
Replace counts of sources and PMIDs with lists

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#210]
Example from DGIdb v2 detailed results:

![image](https://user-images.githubusercontent.com/811065/27868969-0ec9542a-6164-11e7-9cbe-9c28ec7b4a33.png)

Show the first 1 or 2 entries in each column. If more, allow expanding of row to display all entries.

**Comment by yanyangfeng** [comment]
This was fixed with the icon links and lists of PMIDs
