### ISSUE TITLE
about Postgre dump file

### ISSUE THREAD

**Issue by need47** [griffithlab/dgi-db#211]
Could you please include the schema (data definitions) in the [dump file](http://dgidb.genome.wustl.edu/downloads/data.sql)? It seems that the dump file was created with --data-only flag.

**Comment by ahwagner** [comment]
The data are kept separate from the db structure. The structure file is here: https://github.com/griffithlab/dgi-db/blob/master/db/structure.sql

**Comment by need47** [comment]
What a swift response. Thanks a lot.
