### ISSUE TITLE
Create .tsv Downloads of Drugs and Genes

### ISSUE THREAD

**Issue by need47** [griffithlab/dgi-db#218]
First of all, thanks for your hard work on this comprehensive resource. I can see a lot of things going on here. 

It seems that you guys have decided to use ChEMBL id for grouping drugs (based on drugs.chembl_id). That's a good start. I used to check a type field for "PubChem CID" in drug_aliases table in order to get the CID. Now a lot of changes in v3. The closest query I have for the purpose is as follows:
```sql
SELECT a.id drug_id, a.name, b.alias cid 
FROM drugs a 
INNER JOIN drug_aliases b ON b.drug_id=a.id
INNER JOIN drug_aliases_sources c ON c.drug_alias_id=b.id
INNER JOIN sources d ON d.id=c.source_id
WHERE d.source_db_name='PubChem' AND b.alias !~ '[^0-9]'
```
Please correct me if anything is wrong. But the where clause is ugly and not strict.

The reason why I dig so hard directly into the postgresql db is that there is no download option available for drug and drug identifier (ChEMBL ID, PubChem CID, or whatever). Moreover, the download option for gene and gene identifier (i.e. Entrez GeneID) seems gone.
[http://dgidb.genome.wustl.edu/downloads](http://dgidb.genome.wustl.edu/downloads)

**Comment by ahwagner** [comment]
Using ChEMBL as our base resource for drugs allows us to specify a ChEMBL ID (although not necessarily a PubChem CID) for each drug. This is available as a field (`chembl_id`) in the `drugs` table.

Similarly, the `genes` table has an `entrez_id` field that designates a unique Entrez identifier for each gene concept.

**Comment by need47** [comment]
Could you add download options for drugs and genes?

**Comment by ahwagner** [comment]
Sure! It sounds to me like you want: 

genes.tsv:
Gene Claim | Gene Group Name | Entrez ID | Gene Claim Source

drugs.tsv:
Drug Claim | Drug Group Name | ChEMBL ID | Drug Claim Source

correct?

**Comment by need47** [comment]
That's good enough for me. Thanks a lot.

**Comment by need47** [comment]
one more suggestion to [interactions.tsv](http://dgidb.genome.wustl.edu/downloads): could you please add drug and gene identifiers?

**Comment by ahwagner** [comment]
That sounds reasonable. We'll work that in.

**Comment by need47** [comment]
Thanks. I never had an experience with such prompt responses like you :-)

**Comment by ahwagner** [comment]
endpoints for this should also exist as part of #141
