### ISSUE TITLE
new drug-gene interaction sources

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#223]
Additional sources from VICC that could make for good source additions to the DGIdb.

- [x] oncokb
- [x] cgi
- [x] ckb

**Comment by obigriffith** [comment]
+1 This is a great idea. It would tie DGIdb into our VICC efforts and really improve the clinically actionable aspect of DGIdb

**Comment by kcotto** [comment]
oncokb data download page: http://oncokb.org/#/dataAccess
cgi data download page: https://www.cancergenomeinterpreter.org/biomarkers
ckb info: it looks as though this data is not available for download currently (from their FAQ page: https://ckb.jax.org/about/faq)

> Is there a way to download CKB content or an API?
> 
> CKB is continually under development and download of content or an API is not available at this time. We will periodically release new content features and functionalities. If you would like to stay informed of new releases, please email ckbsupport@jax.org with your contact information.
> 
>

**Comment by ahwagner** [comment]
Harvesters exist for all of these resources as part of our VICC efforts (https://github.com/ohsu-comp-bio/g2p-aggregator/tree/v0.4/harvester). Jackson labs has a limited-set API set up, but not publicly announced. OncoKB has an API we can leverage.

**Comment by kcotto** [comment]
Looking at OncoKB's API, it looks like we want to get all of the actionable variants, which provides drug, mutation, cancer type, drug, and PMIDs. 

For CGI, we will want to pull the cancer biomarkers that they provide.

**Comment by susannasiebert** [comment]
@kcotto For OncoKB, did you see a way to get the actionable variants via the API? I'm only seeing a link to download the tsv. The plain variants API endpoint doesn't include any information about the interactions/drugs. We should discuss whether the information information in the actionable variants tsv sufficient or whether we need to scrape the API for additional information we might want.

**Comment by kcotto** [comment]
I think what you are looking for is under the Utils section of the API @susannasiebert `/utils/allActionableVariants`. Also, you can specify if you want it as a text file `/utils/allActionableVariants.txt`

**Comment by susannasiebert** [comment]
Of course it's in the one section that I didn't expand :roll_eyes:

**Comment by susannasiebert** [comment]
For OncoKB it looks like some of the actionable variants show an interaction between one gene an multiple drugs in combination (denoted by a `+`); see, for example, the first entry in http://oncokb.org/api/v1/utils/allActionableVariants. @ahwagner would we skip these interactions or is there a way to represent them in DGIdb?

**Comment by ahwagner** [comment]
I would split them into multiple interaction claims (one for each drug), and add an attribute with `name: combination therapy` and `value: {drug combination}` where `{drug combination}` is the string of drugs concatenated by '+'.

**Comment by susannasiebert** [comment]
Sounds like a plan. We can also hit the gene and drug endpoints to get more information on each of them. For example, both drugs and genes have a list of synonyms we can import as aliases. We should discuss which information we want to include and how (e.g., nomenclatures). I included some suggestions in the examples below:

utils/allActionableVariants:
```
"gene": "PTEN", -> gene claim - name
"variant": "Oncogenic Mutations",
"cancerType": "Prostate Cancer", -> interaction claim attribute
"level": "4",
"drugs": "LY3023414 + Enzalutamide", -> 2 drug claims with associated interaction claim attribute 
"pmids": "21575859", -> interaction claim publication
"abstracts": ""
```

genes/lookup?query=PTEN
```
"entrezGeneId": 5728, -> gene claim alias
"hugoSymbol": "PTEN", -> gene claim name
"name": "phosphatase and tensin homolog", -> gene claim alias
"oncogene": false,
"curatedIsoform": "ENST00000371953",
"curatedRefSeq": "NM_000314.4",
"geneAliases": [
"DEC",
"MHAM",
"TEP1",
"10q23del",
"BZS",
"PTEN1",
"GLM2",
"CWS1",
"MMAC1"
], -> gene claim aliases
"tsg": true
```
drugs/lookup?name=LY3023414&exactMatch=true
```
"drugName": "LY3023414",
"synonyms": [], -> drug claim aliases
"atcCodes": []
```
