### ISSUE TITLE
Create ER diagram for help docs/wiki

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#226]
User requested an ER diagram of the database. To my knowledge, this does not exist.

**Comment by kcotto** [comment]
There's one on confluence: https://confluence.gsc.wustl.edu/display/BIO/DGIdb. Looks like it was last updated in 2013, so I would imagine that some parts of it are outdated.

**Comment by ahwagner** [comment]
New ERD added: https://github.com/griffithlab/dgi-db/blob/master/erd.pdf
