### ISSUE TITLE
Custom source cards for Entrez and ChEMBL

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#244]
Entrez has a source in our database right now, but no gene claims (because they are the base concept of `gene` and are treated differently). The existing ChEMBL source should be renamed to ChEMBL interactions, and a new ChEMBL source should be created for drugs. These two sources (ChEMBL drugs and Entrez genes) will need custom methods written for them in the `PopulateCounters` normalizer.

**Comment by ahwagner** [comment]
Remove genes/drugs panels from sources as appropriate based on source type. Remove trust information panel. Separate out interactions into a new sub-panel.

**Comment by susannasiebert** [comment]
Also discussed: remove inter-gene interactions counter

**Comment by yanyangfeng** [comment]
@ahwagner is someone working on the actual creation of the new sources, or should I tackle that in addition to the normalizer task/views?

**Comment by ahwagner** [comment]
The Entrez source exists already, but the counters are all zeros because as the canonical source there are no associated gene claims. You can start by adjusting the count normalizer to populate the "gene claims" and "grouped claims" to be equal to the total number of genes (DataModel::Gene.count).

The ChEMBL data exist, but no corresponding DataModel::Source exists in the database. I will update and push that change shortly.

**Comment by ahwagner** [comment]
@yanyangfeng this is now merged into `master`, commit c6aafe63bc4dfff24e9ba9c441a2461f710dcf3a. You'll need to update the 'ChemblDrugs' source in the normlizer to reflect the total number of drug groups.
