### ISSUE TITLE
Add summary statistics page

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#256]
- Total Genes
- Total Druggable Genes
- Total Drugs
- Total Interactions

**Comment by yanyangfeng** [comment]
@ahwagner did you envision a separate page entirely or just tacking this info on to say the source page or the getting started page?

**Comment by ahwagner** [comment]
Let's start a new page. It might start off mostly empty, but eventually we could fill it in with graphs _a la_ CIViC: https://civic.genome.wustl.edu/statistics/evidence
