### ISSUE TITLE
rework groupers to optionally operate on a source

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#263]
Currently groupers attempt to group all ungrouped claims. We should add an option to group only claims from a designated source, to speed up grouping operations on single-source updates.

The trade-off is that we will occasionally want to run the full grouper in case previously ungrouped claims from other sources may now group with the addition of claims from the updated source(s). One easy solution for this is to do a full grouper run after one of the weekly recurring updaters.

**Comment by susannasiebert** [comment]
This has been implemented for the new drug grouper but still needs to be added for the new gene grouper. The interaction grouper has been modified to only work in groupable interaction claims (where the associated gene and drug claims have an associated gene and drug, respectively).
