### ISSUE TITLE
DrugBank claims have PMID 0

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#274]
Strange, but somehow all 11293 drugbank interaction claims have an associated PMID of 0. I've cleaned up the database, but we should check the importer to see where things are going wrong.

**Comment by susannasiebert** [comment]
The DrugBank XML changed. I'm working on a fix for the DrugBank XML parser.

**Comment by susannasiebert** [comment]
The publication entry still exists in the database but it doesn't have any linked interactions or interaction claims. Should I make a new data dump with that publication removed?

**Comment by ahwagner** [comment]
Yes, let's do that.

**Comment by susannasiebert** [comment]
A new data dump without this Publication entry has been created and pushed to the data subrepo.
