### ISSUE TITLE
DoCM online updater imports drug claim names with leading spaces.

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/dgi-db#293]
I'm not sure if this needs to be fixed in DoCM or handled by us but the DoCM online updater imports some claim names with a leading whitespace.

Example:
```
#<DataModel::DrugClaim:0x007fe6fbb67710
 id: "070150d6-5fa2-4328-ae48-fc050254052b",
 name: " PKC412",
 nomenclature: "DoCM Drug Name",
 source_id: "b3521d9b-ba98-48b3-9834-e63191146367",
 primary_name: " PKC412",
 drug_id: "ee7f7a80-e97d-4968-9842-07d559733b6e">
```
We should update the online updater to clean up these values before importing.

**Comment by ahwagner** [comment]
This was an issue in ChEMBL too, although I fixed it in that importer. Now that we have a helper class for creating records, maybe we should just do a leading/trailing whitespace strip on any aliases/names/attributes that are entered into the database.

Thoughts?

**Comment by susannasiebert** [comment]
I agree. That sounds like the way to go. I can work on that tomorrow. Should we then import everything from scratch? Just DoCM? I wouldn't be surprised if this is part of the reason for the poor grouping for some of these sources so we should probably also regroup.

**Comment by ahwagner** [comment]
No reason we can't do a full regroup, other than it will take a little more time. I'm all for it 👍

**Comment by susannasiebert** [comment]
I did a full reimport and regroup of all the online updaters locally. Unfortunately, there are still a few sources that are not covered by online updaters that have problems:
- `FDA` has 18 drug_claims with names that start with a whitespace.
- `PharmGKB` has 104 drug_claim_attributes where the name starts with a whitespace.
- `TEND` has 219 drug_claim_attributes where the value starts with a whitespace. It also has 8 gene_claim_attributes where the value starts with a whitespace.
- `HopkinsGroom` has 141 gene_claim_aliases where the alias starts with a whitespace
-  `TTD` and `PharmGKB` together have 51 drug_claim_aliases where the alias starts with a  whitespace.
- `ChemblInteractions` has 1 interaction_claim_attribute where the value starts with a whitespace.
@ahwagner How should I handle these?
