### ISSUE TITLE
broken downloads link

### ISSUE THREAD

**Issue by malachig** [griffithlab/dgi-db#294]
The interactions tsv download appears to be broken.

http://www.dgidb.org/downloads/data/interactions.tsv

**Comment by ahwagner** [comment]
The URL has changed. The download is now: http://dgidb.org/data/interactions.tsv

**Comment by malachig** [comment]
I don't see this update on the live site ...

**Comment by malachig** [comment]
Actually what is happening is that I get the old version of the site here:
http://www.dgidb.org/downloads/

But the new version here:
http://www.dgidb.org/downloads

Interesting.

**Comment by ahwagner** [comment]
Yeah, the trailing slash seems to make a difference. Problem is likely in `config/routes`.

**Comment by susannasiebert** [comment]
I haven't been able to find out much. This url does not get resolved through `config/routes` but instead has a static page at `app/views/static/downloads.html.haml` that gets served directly. Interestingly, the staging environment behavior is as expected and both pages contain the correct links. I'm really not sure what is going on here.

**Comment by ahwagner** [comment]
This was an issue with passing relative paths to `link_to`. Changed to absolute paths, now resolves correctly regardless of `dgidb.org/downloads` or `dgidb.org/downloads/` view.
