### ISSUE TITLE
Edit DoCM citation on sources page to point to publication 

### ISSUE THREAD

**Issue by kcotto** [griffithlab/dgi-db#295]
The DoCM citation currently reads "Manuscript in preparation. Please cite http://docm.genome.wustl.edu/". We should fix this to point to the publication (http://www.nature.com/nmeth/journal/v13/n10/full/nmeth.4000.html)

**Comment by susannasiebert** [comment]
This needs to be fixed in `lib/genome/online_updaters/docm/updater.rb`. @kcotto can you tell me what the exact citation should be and I'll update the above file as well as the database entry on the live site.

**Comment by kcotto** [comment]
DoCM: a database of curated mutations in cancer. Ainscough BJ, Griffith M, Coffman AC, Wagner AH, Kunisaki J, Choudhary MN, McMichael JF, Fulton RS, Wilson RK, Griffith OL, Mardis ER. Nat Methods. 2016;13(10):806-7. PMID: 27684579

**Comment by susannasiebert** [comment]
This is fixed.
