### ISSUE TITLE
link to actual source page for interaction claim

### ISSUE THREAD

**Issue by yang-yangfeng** [griffithlab/dgi-db#304]
As per @obigriffith, it's not clear if or how we do this, currently. For each interaction claim, we want to be able to link directly to the actual source page from which we obtained information for the claim.

**Comment by yanyangfeng** [comment]
tooltip on inactive link when not possible

**Comment by obigriffith** [comment]
+1. This would solve problem of users wanting access to some non-imported meta-data for some sources (e.g., CIViC)

**Comment by susannasiebert** [comment]
For CIViC specifically, we actually only create one interaction claim for multiple evidence items. Each drug name in CIViC results in one drug claim and each gene name results in one gene claim. If multiple evidence items uses the same drug (claim) and gene (claim), we are then reusing the same interaction claim for that specific drug claim-gene claim-combination. I think this is something we're doing at least for other online updaters as well. I'm actually wondering if we need to change this behavior to ensure that each evidence item creates a separate interaction claim. 

We then need to decide how we want to save the outside source url for a specific claim. Would it be an attribute on the claim? On the publication? Totally new table?

**Comment by susannasiebert** [comment]
The remaining Sources that I haven't added a link for are:
-  Cancer Commons
-  Clearity Foundation Biomarker
-  Clearity Foundation Clinical Tria

It was decided to add the TSVs for these sources to the downloads folder and the linkouts fill point to them.
