### ISSUE TITLE
Fix GO online updater and check linkout doesn't include subsets of genes

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#317]
In our online GO importer, we pull terms using the generated URL at https://github.com/griffithlab/dgi-db/blob/master/lib/genome/online_updaters/go/api_client.rb#L22.

For reasons that aren't clear to me (and are likely internal to geneontology.org), doing a search on a term without quotes results in a superset of gene identifiers that are associated with that term, and other genes that are not.

For example:
(Nuclear Hormone Receptor term, GO:0004879, with quotes):
http://golr.geneontology.org/select?defType=edismax&qt=standard&indent=on&wt=csv&rows=100000&start=0&fl=bioentity_label,bioentity,source,synonym&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&csv.encapsulator=&csv.separator=%09&csv.header=false&csv.mv.separator=%7C&fq=document_category:%22bioentity%22&fq=taxon_subset_closure_label:%22Homo%20sapiens%22&facet.field=source&facet.field=taxon_subset_closure_label&facet.field=type&facet.field=panther_family_label&facet.field=annotation_class_list_label&facet.field=regulates_closure_label&q=%22GO:0004879%22&qf=bioentity%5E2&qf=bioentity_label_searchable%5E2&qf=bioentity_name_searchable%5E1&qf=bioentity_internal_id%5E1&qf=synonym%5E1&qf=isa_partof_closure_label_searchable%5E1&qf=regulates_closure%5E1&qf=regulates_closure_label_searchable%5E1&qf=panther_family_searchable%5E1&qf=panther_family_label_searchable%5E1&qf=taxon_label_searchable%5E1

(NHR term without quotes):
http://golr.geneontology.org/select?defType=edismax&qt=standard&indent=on&wt=csv&rows=100000&start=0&fl=bioentity_label,bioentity,source,synonym&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&csv.encapsulator=&csv.separator=%09&csv.header=false&csv.mv.separator=%7C&fq=document_category:%22bioentity%22&fq=taxon_subset_closure_label:%22Homo%20sapiens%22&facet.field=source&facet.field=taxon_subset_closure_label&facet.field=type&facet.field=panther_family_label&facet.field=annotation_class_list_label&facet.field=regulates_closure_label&q=GO:0004879&qf=bioentity%5E2&qf=bioentity_label_searchable%5E2&qf=bioentity_name_searchable%5E1&qf=bioentity_internal_id%5E1&qf=synonym%5E1&qf=isa_partof_closure_label_searchable%5E1&qf=regulates_closure%5E1&qf=regulates_closure_label_searchable%5E1&qf=panther_family_searchable%5E1&qf=panther_family_label_searchable%5E1&qf=taxon_label_searchable%5E1

A user wrote us stating that `DRD2`, `DRD3`, and `DRD4` do not belong in the NHR category. On review, this statement matches what geneontology provides if you search for `GO:0004879` or `DRD2` individually through the web interface. Consequently, we should be doing queries _with_ quotes, and update our database accordingly.

**Comment by kcotto** [comment]
Neither of these links no longer works. I will be work on updating the API link and investigate whether or not this quote vs non-quote issue still exists.

**Comment by kcotto** [comment]
#461 addresses this
