### ISSUE TITLE
import dgidb-data.sql to a local postersql database error

### ISSUE THREAD

**Issue by zhilongjia** [griffithlab/dgi-db#323]
When importing dgidb-data.sql (downloaded from http://dgidb.org/data/data.sql days ago) to a created postersql database via
`psql dgidb < /data/dgidb/data.sql`, it
outputs:
`ERROR:  relation "ar_internal_metadata" does not exist
invalid command \.
ERROR:  syntax error at or near "environment"
LINE 1: environment development 2017-10-12 15:50:11.886845 2017-10-1...`

My postgresql version: psql (9.6.6). I'm not sure it's related to the PostgreSQL version. Thank you.

**Comment by jkanche** [comment]
Hello, I'm having the same issue trying to import the data file ( i've use 9.6.3 since the dump file was created using postgres 9.6.3).

any updates on this issue ? or can you create a new data file ? 

Thanks!

**Comment by ahwagner** [comment]
This is an occasional problem for people looking to stand up a local version of the DGIdb. We will investigate a more robust method utilizing our new git data repo that should circumvent this. Please remain subscribed to this issue for progress.

**Comment by susannasiebert** [comment]
The DGIdb data downloads page (http://dgidb.org/downloads) has updated instructions how to download and import the most up-to-data dump into your local database.
