### ISSUE TITLE
Browse sources display glitch

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/dgi-db#331]
I'm seeing overlap between the navigation side bar and entries on the browse sources page. 

<img width="1275" alt="Screenshot 2019-07-22 10 18 25" src="https://user-images.githubusercontent.com/1638042/61644407-33f95580-ac6a-11e9-914e-cf1c998d1a00.png">

**Comment by susannasiebert** [comment]
#405 resolved this issue by moving the source types menu above the list
