### ISSUE TITLE
Query overlap score

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#340]
If multiple queried genes match to a drug, we should indicate that in some way

**Comment by ahwagner** [comment]
See visualization in #166.

Consider visualizing in similar way, and taking into account interaction specificity.

**Comment by susannasiebert** [comment]
There should be some sort of penalty for drugs that interact with a lot of genes

**Comment by ahwagner** [comment]
For each gene:
1) how many drugs overlap other results
2) mechanism of action?
3) measure promiscuity of drug
4) increase score if multiple sources report it

this score should apply conversely for drug searches

**Comment by ahwagner** [comment]
@susannasiebert to create initial metric proposal with above characteristics

**Comment by susannasiebert** [comment]
![D03B36D3-72FB-4BCA-8F71-B13652479A92](https://user-images.githubusercontent.com/6617192/67965508-2855ed00-fbd0-11e9-91ad-4cf551968007.jpeg)
