### ISSUE TITLE
Add DGIdb concepts to NDEX

### ISSUE THREAD

**Issue by malachig** [griffithlab/dgi-db#343]
Similar to how we did with CIViC we should define some networks for key DGIdb relationship and create an automatic task for updating these in NDEX.  Perhaps Rudolf Pillich can help advise us on that.

**Comment by ahwagner** [comment]
@malachig to contact Rudy and Dexter about setting up this integration

**Comment by malachig** [comment]
I reached out to them.

**Comment by ahwagner** [comment]
@malachig did this happen, is there something we could point to for manuscript?

**Comment by malachig** [comment]
NDEX has been waiting for our feedback on this test network:

http://www.ndexbio.org/#/network/a57828de-d8e0-11e9-bb65-0ac135e8bacf?accesskey=631e8d14271c7e6d2ef2ca68fa30ed0f7cebf7048a6f40d163c7d0965d5da97a
