### ISSUE TITLE
Add directionality to interactions

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#347]
Curate and add a simple "inhibits" / "activates" column on interaction claims and groups.

**Comment by ahwagner** [comment]
@sharonfreshour to investigate sources and strategies for incorporating this into interaction claims and groups.

**Comment by sharonfreshour** [comment]
Here is a link to the spreadsheet I have for the interaction types: https://docs.google.com/spreadsheets/d/1IvzP7YtaN1XYEtrcAGTGIgNgl3eLTiFpxpSwli7DHNs/edit?usp=sharing

If anyone has feedback on interactions I've marked as Inhibitor/Activator feel free to add it.

**Comment by ahwagner** [comment]
@sharonfreshour is working on finding existing sources for this information for our next meeting.

**Comment by ahwagner** [comment]
@sharonfreshour to:

* migrate spreadsheet to DGIdb getting started table
* do a database migration to add field for directionality
* survey of missing / unidirectional / conflicting results after grouping interactions

Anticipated completion: October 17th

Planned database migration is to add directionality field directly to interaction types
