### ISSUE TITLE
DGIdb v4 Target Journals

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#351]
Currently considering:
- NAR Database (no earlier than June 1, 2020)
- Bioinformatics Application Note
- Database - Journal of Biological Databases and Curation

**Comment by obigriffith** [comment]
Sept 15 deadline for update papers

**Comment by kcotto** [comment]
To check the suitability of the proposed submission, the authors should contact Prof. Daniel J. Rigden, Executive Editor of the NAR Database Issue, at nardatabase@gmail.com by July 1st at the latest.

**Comment by kcotto** [comment]
Decided to go with NAR database.
