### ISSUE TITLE
add scores to API results

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#353]
We currently have interaction scores on the website, but not in our interactions API. We should revise our API to return these as well.

**Comment by susannasiebert** [comment]
The updated query score depends on the other results in the search space. So for an individual interaction, the score is not meaningful/can't be calculated.

**Comment by susannasiebert** [comment]
The score does get returned on the api endpoint for interaction searches.

**Comment by susannasiebert** [comment]
During today's meeting we discussed implementing an additional global interaction score to be displayed on a particular interaction in addition to the new query-specific interaction score.
