### ISSUE TITLE
Normalize Interaction Types

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/dgi-db#367]
Right now we have duplicate InteractionClaimTypes in the database that only differ in their capitalization. We should normalize them:

- Make a list of the existing values to ensure that there aren't any values we don't want
- Lowercase the existing values, remove duplicate values and reassign linked interactions/interaction claims to the remaining value
- Add some database constraints to the `type` column to a) enforce lowercasing and b) enforce unique values
- Update the importers to not create new InteractionClaimTypes and instead fail if an interaction type is not found

The `downcase` and `uniq` calls in https://github.com/griffithlab/dgi-db/pull/366 should be removed.

This might be related to issue: https://github.com/griffithlab/dgi-db/issues/202

**Comment by kcotto** [comment]
I've included two files below. Unlisted_interactions.txt specifies sources found within dgidb that are not on the getting started page and vice versa. Novel_interactions_wsources.txt is a tsv file with a header that maps the missing interaction types to their sources of origin. DrugBank, GuideToPharmacologyInteractions, and TTD are the sources for these interaction types that we currently don't have in our definition table.
[unlisted_interactions.txt](https://github.com/griffithlab/dgi-db/files/4424604/unlisted_interactions.txt)
[novel_interactions_wsources.txt](https://github.com/griffithlab/dgi-db/files/4424605/novel_interactions_wsources.txt)

**Comment by ahwagner** [comment]
@kcotto to harmonize the unlisted_interactions.txt with existing table entries

**Comment by kcotto** [comment]
[interaction_changes.txt](https://github.com/griffithlab/dgi-db/files/4523774/interaction_changes.txt)

Here's a file containing proposed changes for unlisted interaction types.

**Comment by ahwagner** [comment]
@susannasiebert to take this mapping and normalize to these terms
