### ISSUE TITLE
Fix Guide to Pharmacology Interactions importer

### ISSUE THREAD

**Issue by kcotto** [griffithlab/dgi-db#378]
Received the following text in an email:

"I am emailing you because I found a potential interaction between methionine and a galanin receptor, found in this page
 
http://www.dgidb.org/interaction_claims/bbd47d47-f26a-49fc-ad85-0063a160af70
 
I see it comes from the Guide to pharmacology interactions, but I am unable to find this interaction in their website, specifically in the link https://www.guidetopharmacology.org/GRAC/FamilyDisplayForward?familyId=27"

After doing some investigating, it appears that this is a false interaction that was created due to the Guide to Pharmacology ID mapping as an alternate name for Methionine. This is something that we should discuss fixing in this next update. Specifically, we don't need to bring in the Guide to Pharmacology ID as I think that's unique to their database.

**Comment by susannasiebert** [comment]
We are currently using the `ligand_id` as the `name` when creating the `drug_claim` and `ligand` as the `primary_name`. Are you suggesting to use the `ligand` value for both fields then? What about the gene claims where we currently use the `target_id`?

**Comment by kcotto** [comment]
I suggest using `ligand_puchem_sid` instead of `ligand_id`. It's the pubchem substance id, which I think we are already pulling into the database elsewhere.

Instead of using the `target_id` we should probably use `target_ensembl_gene_id` since we are also pulling in ensembl.

**Comment by susannasiebert** [comment]
Sounds good. I will make those changes.

**Comment by susannasiebert** [comment]
A couple of observations I made:
- It looks like not every entry in the csv that has a `target_id` also has `target_ensembl_gene_id`.
- Some `target_ensembl_gene_id` values are actually multiple gene IDs, separated with a `|`. I assume we can create multiple gene claims in these cases?

**Comment by kcotto** [comment]
- I'd say if they don't have a `target_ensembl_gene_id` then we just don't include it in the import. Otherwise we might still end up creating erroneous interaction claims.
- I think creating multiple gene claims is the right way to go. It seems like these lines are describing gene families or genes with multiple subunits.

Happy to discuss this more on Thursday though.
