### ISSUE TITLE
Implement global interaction score and add to API endpoint

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/dgi-db#402]

**Comment by susannasiebert** [comment]
The revised query score implemented in #360 is:
![chart](https://user-images.githubusercontent.com/6617192/86134529-5a955280-baaf-11ea-8c43-032061adf722.png)
So if we remove the `overlapcount` this would become:
![chart (1)](https://user-images.githubusercontent.com/6617192/86134686-8ca6b480-baaf-11ea-9e96-6e9c151859a5.png)
@ahwagner is that what you were imagining for the interaction score?

**Comment by ahwagner** [comment]
Not quite-sorry for the confusion. Here's how I see Query Interaction and Interaction scores:

https://docs.google.com/presentation/d/1L4PAwZJDa4-5M87HCxU2tKgv4qD6H9TVLF8gxpZWvWY/edit?usp=sharing
