### ISSUE TITLE
Reimport TTD data

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/dgi-db#407]
TTD updated the format of their internal identifiers. We should reimport their data so we get the up-to-date identifiers. This is also needed to make the interaction source linkouts for this source work.

**Comment by ahwagner** [comment]
They also changed their root URL, now at: http://db.idrblab.net/ttd/

**Comment by ahwagner** [comment]
This is ridiculous. http://bidd.nus.edu.sg/group/ttd/ttd.asp gets you a 404. Going to the site root redirects you to http://bidd.nus.edu.sg/group/bidd.htm, with a giant banner and button telling you to go to TTD on their other domain... http://db.idrblab.net/ttd/.

WTF.

Anyway, we should use http://db.idrblab.net/ttd/.

**Comment by susannasiebert** [comment]
The spreadsheet has a MOA column with the following values:
```
'Regulator (upregulator)', 'Suppressor', 'Cofactor', 'Inducer', 'Opener', 'Disrupter', 'CAR-T-Cell-Therapy(Dual specific)', 'Inhibitor; Antagonist; Blocker', 'Intercalator', 'Inhibitor (gating inhibitor)', 'Regulator', 'Agonist', 'Immunomodulator ', 'Modulator', '.', 'Enhancer', 'Immunomodulator (Immunostimulant)', 'MOA', 'Inverse agonist', 'Inhibitor', 'Binder', 'Binder (minor groove binder)', 'Blocker (channel blocker)', 'Stimulator', 'siRNA drug', 'Modulator (allosteric modulator)', 'Partial agonist', 'antagonist', 'Immunomodulator', 'Stablizer', 'Reactivator', 'Immune response agent', 'Activator', 'Antisense ', 'Breaker', 'CAR-T-Cell-Therapy', 'Antagonist', 'Co-agonist', 'Immunostimulant', 'Ligand', 'Agonis; Inverse agonist', 'Blocker'
```
I could use some help normalizing these values.

**Comment by susannasiebert** [comment]
'Regulator (upregulator)', -> 
'Suppressor', -> suppressor
'Cofactor', -> cofactor
'Inducer', -> inducer
'Opener', 
'Disrupter', 
'CAR-T-Cell-Therapy(Dual specific)', -> immunotherapy
'Inhibitor; Antagonist; Blocker', 
'Intercalator', -> negative modulator
'Inhibitor (gating inhibitor)', -> inhibitor
'Regulator', ->
'Agonist', -> agonist
'Immunomodulator ', -> immunotherapy
'Modulator', -> modulator
'Enhancer', 
'Immunomodulator (Immunostimulant)', -> immunotherapy
'Inverse agonist' , -> inverse agonist 
'Inhibitor', -> inhibitor
'Binder', -> binder
'Binder (minor groove binder)', -> binder
'Blocker (channel blocker)', -> blocker
'Stimulator', -> stimulator
'siRNA drug', 
'Modulator (allosteric modulator)', -> allosteric modulator 
'Partial agonist', -> partial agonist
'antagonist', -> antagonist
'Immunomodulator', -> immunotherapy
'Stablizer', 
'Reactivator', 
'Immune response agent', 
'Activator', -> activator
'Antisense ', -> antisense oligonucleotide
'Breaker', 
'CAR-T-Cell-Therapy', -> immunotherapy
'Antagonist', -> antagonist
'Co-agonist', 
'Immunostimulant', 
'Ligand', -> ligand
'Agonis; Inverse agonist', -> inverse agonist 
'Blocker' -> blocker

**Comment by kcotto** [comment]
Here's my best guess filling in. 

'Regulator (upregulator)', -> positive modulator
'Suppressor', -> suppressor
'Cofactor', -> cofactor
'Inducer', -> inducer
'Opener', -> potentiator
'Disrupter', -> negative modulator
'CAR-T-Cell-Therapy(Dual specific)', -> immunotherapy
'Inhibitor; Antagonist; Blocker', -> inhibitor
'Intercalator', -> negative modulator
'Inhibitor (gating inhibitor)', -> inhibitor
'Regulator', -> modulator
'Agonist', -> agonist
'Immunomodulator ', -> immunotherapy
'Modulator', -> modulator
'Enhancer', -> positive modulator
'Immunomodulator (Immunostimulant)', -> immunotherapy
'Inverse agonist' , -> inverse agonist
'Inhibitor', -> inhibitor
'Binder', -> binder
'Binder (minor groove binder)', -> binder
'Blocker (channel blocker)', -> blocker
'Stimulator', -> stimulator
'siRNA drug', -> antisense oligonucleotide
'Modulator (allosteric modulator)', -> allosteric modulator
'Partial agonist', -> partial agonist
'antagonist', -> antagonist
'Immunomodulator', -> immunotherapy
'Stablizer', -> chaperone
'Reactivator', -> activator
'Immune response agent',
'Activator', -> activator
'Antisense ', -> antisense oligonucleotide
'Breaker', -> binder
'CAR-T-Cell-Therapy', -> immunotherapy
'Antagonist', -> antagonist
'Co-agonist', -> agonist
'Immunostimulant',  -> I think this should be a new category? If not, then maybe activator?
'Ligand', -> ligand
'Agonis; Inverse agonist', -> inverse agonist
'Blocker' -> blocker
