### ISSUE TITLE
Capitalization of drug names not consistent

### ISSUE THREAD

**Issue by kcotto** [griffithlab/dgi-db#428]
Some drug names are fully capitalized and others just have the first letter capitalized.

<img width="1092" alt="Screen Shot 2020-08-06 at 11 56 28 AM" src="https://user-images.githubusercontent.com/22246534/89559990-fcf5d380-d7db-11ea-975a-891df8d96bce.png">

**Comment by susannasiebert** [comment]
A lot of importers are set to upcase the drug names. We need to go through the list of importers and identify the ones that are not doing this. Alternatively, we might also just normalize this in the drug grouper. @ahwagner thoughts?

**Comment by acoffman** [comment]
Personally, I would lean towards a final pass that just uppercases them all (ie: in the grouper or something) rather than relying  on each individual importer to remember to do it, but I don't have a strong preference either way. Whatever @ahwagner thinks is best is good with me.
