### ISSUE TITLE
Revisit Drug Grouper

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#44]
Drug claims aren't grouping well. Things like HG2+ (an alias of "MERCURIC ION" in PubChem, and an alias to GTP Ligand 4215) represent the same concept, but don't group, such that some drug-gene interactions display as "no matches" for these drugs. This may be fixed with @acoffman's PubChem importer ( #41). Will investigate soon.

**Comment by ahwagner** [comment]
A related issue is that some drugs--such as monoclonal antibodies--are substances but not compounds. Since we use the compound ID file from PubChem, these substances get grouped incorrectly (if at all).

**Comment by ahwagner** [comment]
This should be addressed by adding support for SID lookups if CID fails. This should be addressed in the v3 milestone.

**Comment by malachig** [comment]
This is really unfortunate, many of the newest, most interesting and promising cancer therapies are now antibody therapies.  While the technical reason makes sense as described here, to most users of DGIdb, it will not be intuitive that drugs such as Trastuzumab/Herceptin are not displayed for a query of ERBB2/HER2 for example.  :(.  

Is it not practical to simply merge substance/compound for the purposes of this grouping?

**Comment by ahwagner** [comment]
@malachig, I completely agree. @obigriffith and I discussed this a while back, and the plan is to add support for PubChem substances as secondary base records.

**Comment by ahwagner** [comment]
per today's discussion, we should investigate grouping by DrugBank/ChEMBL + PubChem Substance ID instead of just PubChem. @gspies and @acoffman will take a look at this.

**Comment by ahwagner** [comment]
related issue reported by user: 

> I do a search for the drug DICLOFENAC.
> The web-based request returns 9 drug-gene interactions while the downloadable spreadsheet (interactions.tsv) shows 11 interactions. 
> Two genes ( CYP2C9 and CYP2J2.) are missing when I am searching on the website.

It appears that the drug claims for these genes do have the DICLOFENAC drug alias (among many other aliases) but are not grouped correctly. Investigating in parallel with my evaluation of @gspies [grouper update](https://github.com/genome/dgi-db/tree/add-test-to-grouper).

**Comment by ahwagner** [comment]
@gspies: great job on this. Adding DrugBank increased our overall drug grouping by ~14%.

Next, we should investigate some of the remaining drug claims that aren't grouping to determine what's going wrong. I've updated the [grouper update](https://github.com/genome/dgi-db/tree/add-test-to-grouper) branch with a few small changes from my review. @gspies, Checkout the branch and sub-repo, then load up the `data.sql` dump from the recent sub-repo commit (`dedup-data` branch @ `8c90d5f`). Ask @acoffman for help with this if you get stuck. Start by investigating why the above interactions (CYP2C9 and CYP2J2 with DICLOFENAC) aren't grouping to the drug, and see if you can patch it. After that, we should review some of the larger resources, starting with `GuideToPharmacologyInteractions`.

**Comment by ahwagner** [comment]
In addition, we should now investigate why drugs are returning as "ambiguous" with multiple records with exactly the same name.

**Comment by ahwagner** [comment]
Update: It looks like there are 12,839 `drug` entities with associated `drug claims`, but 14,828 with NO associated claims.

There are no entries with no `drug claims` that are associated with interactions, which is good. I've removed the 14,828 drug entities in commit `XXX`, but we should ensure this is not a re-emerging artifact.

TODO: Run the grouper, see if this re-emerges.

![screen shot 2017-04-18 at 1 33 02 pm](https://cloud.githubusercontent.com/assets/811065/25147003/96cce8fc-243b-11e7-850f-737de7440e14.png)

**Comment by ahwagner** [comment]
this will be addressed by the changes in #148
