### ISSUE TITLE
Normalize DrugBank interaction types

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/dgi-db#500]
The reimport of DrugBank has introduced a number of new interaction types. These need to be normalized or, for the ones we want to keep, we need to add a directionality, description, and reference:
```
"substrate", 
"weak inhibitor", 
"protector", 
"downregulator", 
"inactivator", 
"degradation", 
"oxidizer", 
"aggregation inhibitor", 
"coating agent", 
"dilator", 
"deoxidizer", 
"diffusing substance", 
"nucleotide exchange blocker", 
"vesicant", 
"inhibition of synthesis", 
"stabilization", 
"translocation inhibitor", 
"gene replacement", 
"inhibits downstream inflammation cascades"
```

**Comment by susannasiebert** [comment]
The following types do not have any interactions (only ungrouped interaction claims):
```
"oxidizer",
"coating agent",
"dilator",
"deoxidizer", 
"diffusing substance", 
"nucleotide exchange blocker", 
"vesicant",
"stabilization",
"translocation inhibitor", 
"gene replacement"
```

**Comment by susannasiebert** [comment]
`weak inhibitor`, `substrate`, and `downregulator` were also used by a number of other sources but are missing their directionality, description, and reference

**Comment by kcotto** [comment]
Here's what I think is the best way to normalize these interaction types

"substrate": 'SUBSTRATE',
"weak inhibitor": 'INHIBITOR',
"protector": 'OTHER',
"downregulator": 'NEGATIVE MODULATOR',
"inactivator": 'INACTIVATOR',
"degradation": CLEAVAGE,
"oxidizer": 'OTHER',
"aggregation inhibitor": 'INHIBITOR',
"coating agent": 'OTHER',
"dilator": 'OTHER',
"deoxidizer": 'OTHER',
"diffusing substance": 'OTHER',
"nucleotide exchange blocker": 'BLOCKER',
"vesicant": 'OTHER',
"inhibition of synthesis": 'INHIBITOR',
"stabilization": 'CHAPERONE',
"translocation inhibitor": 'INHIBITOR', 
"gene replacement": 'OTHER',
"inhibits downstream inflammation cascades": 'INHIBITOR'

**Comment by susannasiebert** [comment]
That sounds good to me and I can work on making this change. It looks like this will add `SUBSTRATE` as a new interaction type so we need a description, a direction, and a reference for it.

**Comment by kcotto** [comment]
Description: Substrates are drugs which are metabolized by the protein they are interacting with.
Direction: N/A
Reference: [FDA - Table of Substrates, Inhibitors and Inducers](https://www.fda.gov/drugs/drug-interactions-labeling/drug-development-and-drug-interactions-table-substrates-inhibitors-and-inducers)

If we're not happy with that reference, we can pull pubmed ids

**Comment by susannasiebert** [comment]
Just realized that INACTIVATOR will also be a new interaction type so we'll need a description, a direction, and a reference for it as well.

**Comment by kcotto** [comment]
Let's normalize INACTIVATOR to INHIBITOR. I think that's a better way than having it be its own interaction type.
