### ISSUE TITLE
Server error using API

### ISSUE THREAD

**Issue by aricht** [griffithlab/dgi-db#520]
Hi all,
thank you very much for maintaining the resource dgidb.org

This week we experience difficulties using the API of dgidb.org. When testing the simple example calls from the DGIdb API documentation one first gets redirected to use`https` instead of `http`. This is the same for API v1 and v2.

When trying to reach the `https` address using API v2 the output is an error:
```
curl https://dgidb.org/api/v2/interactions.json?genes=FLT3
{"status":500,"error":"Internal Server Error"}
```
The same error message is received in the browser. 
On the other hand, the deprecated API v1 seems to work fine.
```
curl https://dgidb.org/api/v1/interactions.json?genes=FLT3
{"matchedTerms":[{"searchTerm":"FLT3","geneName":"FLT3","geneLongName":"FMS RELATED TYROSINE KINASE 3", ...
```
Is this indeed an error from the database side? If yes, do you have an estimate when the service might be available again?

Thank you very much in advance!
Anne

**Comment by susannasiebert** [comment]
Hi Anne,
We recently released DGIdb 4.0 and this looks like a bug introduced during this update. I'm looking into it and apologize for the inconvenience.
Susanna

**Comment by susannasiebert** [comment]
This issue should now be fixed. I also updated the documentation to reflect the switch to https. Please give it a try and let me know if you're still encountering errors.

**Comment by aricht** [comment]
Hi Susanna,
API v2 seems to be working fine now.
Thank you very much for the fast response and fix!
Anne
