### ISSUE TITLE
revise category selection form on druggable_gene_categories page

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#53]
Current sources look a little sloppy. Moving the _Limit categories to specific sources:_ text may help with this.

**Comment by ahwagner** [comment]
![screen shot 2017-04-20 at 2 29 27 pm](https://cloud.githubusercontent.com/assets/811065/25249006/dcd54830-25d5-11e7-80dc-9d856c68fd48.png)

**Comment by yanyangfeng** [comment]
are we happy with how this looks now?

<img width="1325" alt="screen shot 2017-08-21 at 6 34 09 pm" src="https://user-images.githubusercontent.com/16638655/29542257-63707048-869f-11e7-8250-5fd20e6dfe83.png">

**Comment by ahwagner** [comment]
Yes!
