### ISSUE TITLE
Query Score and Interaction Score

### ISSUE THREAD

**Issue by grimwoo** [griffithlab/dgi-db#545]
Hi, as a freshman using DGIdb, could you please let me know the meaning of query score and interaction score?
 
I tried reading your fabulous paper, _Integration of the Drug-Gene Interaction Database (DGIdb) with open crowdsource efforts_, but still, I am not familiar with those two scores.
 
Could I think this way ? : a larger query score and a larger interaction score could result in greater possibility to inhibit the corresponding gene, if "Interaction Type & Directionality" shown "inhibitor (inhibitory)".

**Comment by malachig** [comment]
These scores have been updated / are new features of DGIdb. They are described in our latest paper which we hope will be published soon. For now we have a preprint. Here's the link:

https://www.biorxiv.org/content/10.1101/2020.09.18.301721v1

See figure 3.

Please let us know if this is still not clear.

**Comment by grimwoo** [comment]
@malachig Thanks for your early reply. I have read the paper before posting this issue, and I have to select one or two drug for the validation of my gene list. Hence, I wonder how to choose the drug with relatively high possibility of inhibition.
