### ISSUE TITLE
website inaccessible

### ISSUE THREAD

**Issue by sky-gazer** [griffithlab/dgi-db#549]
yesterday had to bypass certificate issues today cannot access website at all

**Comment by susannasiebert** [comment]
I apologize for this problem. We had to reboot the box. It should be back up now. Please give it a try and see if you are still encountering errors. If you do, can you please provide us more information about how you are accessing dgidb (e.g. are you using https or http, what browser are you using, etc.?

**Comment by sky-gazer** [comment]
The website works just fine now. Thankyou
