### ISSUE TITLE
Keep previously viewed tab on results page in foreground when returning to page

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#67]
When you press the browser "back" button from a result, it should return you to the previous tab (such as "primary interactions"). Instead, the default view ("by source") is displayed.

**Comment by ahwagner** [comment]
This is partially addressed in #103, although it only takes you back to the previous tab, not necessarily the same page of results on that tab.

**Comment by ahwagner** [comment]
part of #124

**Comment by yanyangfeng** [comment]
I believe this is done.
