### ISSUE TITLE
Review TTD alternate names

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#73]
TTD has multiple identifiers as alternate names that are erroneous. For instance, the TTD entries for BALICATIB and RITUXIMAB share Pubchem compound identifiers, but these are distinct drugs. Likewise, the TTD entries for RITUXIMAB and IBRITUMOMAB share the same CAS number. This leads to terrible drug groupings and headaches.

**Comment by ahwagner** [comment]
@kkrysiak, does this look like something you want to tackle?

**Comment by kkrysiak** [comment]
Right off the bat I can say that Rituximab is an antibody which wouldn't ordinarily be captured in the pubchem compound section (no CID), but under the substance section. I see a few other issues with out input TTD file (antibody interaction_types mislabeled, etc).  

We are currently using 4.3.02 (released August 2011). So I'm going to take a look to see if they have a more recent release that perhaps fixed some of these issues for us.

**Comment by kkrysiak** [comment]
For my records, current TTD data downloads - http://database.idrb.cqu.edu.cn/TTD/TTD_Download.asp

**Comment by ahwagner** [comment]
For our records, updated host: http://bidd.nus.edu.sg/group/ttd/TTD_Download.asp

**Comment by obigriffith** [comment]
We will likely update TTD to latest version which might fix some issues. Also, switching from current drug grouping to new VICC drug normalization service deprecates this issue.
