### ISSUE TITLE
Add variant-level metadata from CIViC and DoCM

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#74]

**Comment by ahwagner** [comment]
should be part of #148

**Comment by obigriffith** [comment]
There is a huge amount of variant data for many CIViC genes and this level of meta-data, for a relatively small fraction of DGIdb drug-gene interactions seem unnecessary. Instead we should just link to appropriate CIViC gene or variant pages from CIViC interaction claims.
