### ISSUE TITLE
Ideally search-by-drug would allow some filtering for drug-centric features

### ISSUE THREAD

**Issue by malachig** [griffithlab/dgi-db#81]
Currently none of the filter options available in the interface allow for criteria of the drugs themselves to be focused.  Mechanism of action relates to the nature of the interaction and is often something closely associated with the drug. But it would be great to eventually incorporate some more key metadata on the drugs that could then be the subject of useful filtering.  For example, FDA approval status, additional broad classes beyond anti-neoplastic, delivery method (e.g. oral delivery only), etc...

**Comment by susannasiebert** [comment]
We have filters for  `Approved`, `Antineoplastic`, and `Immunotherapies`. Closing this issue.
