### ISSUE TITLE
Review interaction types

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#84]
@obigriffith @malachig 

I’m thinking about merging and removing a few interaction types.

First, antisense oligonucleotide and antisense are the same thing. I propose we stick to antisense oligonucleotide.

Second, we should remove “immunotherapy”. It was only used by MyCancerGenome, for these three drugs:
Resveratrol, docetaxel, thalidomide.
Basically, these drugs target immunomodulatory targets (PDCD1, CD274, IL6R)—this is not an interaction type, but a target type.

Third, we should remove “product of”. It is used for seven drugs:
Creatine, Choline, L-Methionine, L-Glutamine, Riboflavin, Adenosine monophosphate, Spermine

This interaction is the creation of these endogenous drugs by their “target".

I'm hesitant about "stimulator" and "suppressor". These are used by DrugBank and TTD, and are more of the result of the drug interacting with the target, not the mechanism by which the drug interacts with the target. 14 drugs and 2 drugs, respectively.

Let me know what you think.

**Comment by obigriffith** [comment]
For #1 that is straightforward and I agree the more comprehensive "antisense oligo..." name is a good choice.

I would say that immunotherapy could be considered a drug class defined by the target type. This is going to be an increasingly interesting class of drugs and so it would be nice to be able to represent and filter on them. There are pros and cons to allowing this as an interaction type. 

We should perhaps avoid equating gene with target. For many drug-gene interactions/associations the gene is the target of the drug. But, not for all interactions? If interaction type is really describing "association type" then "product of" might be a valid type. Although, if it is so rare and somewhat confusing in most contexts then maybe there is a good argument for dropping it. 

It is not clear to me why stimulator/suppressor are any less valid than inhibitor?  You could say that also is not the mechanism by with the drug interacts with the target but the result of the drug interacting with the target. But, I would argue the interaction type inhibitor is perhaps the most commonly sought interaction type. No?

**Comment by ahwagner** [comment]
I agree with the sentiment that immunotherapy as a drug class is a useful piece of information to filter on. My only concern is that this is not a true "interaction type" (which is what we're filtering) and represents a very small percentage of the overall interactions in DGIdb.

Of course, this is why I brought up the issue--it's really a question of whether or not we WANT filters in the "interaction type" multiselect box that don't define the interactions themselves. I can see the value of keeping immunotherapy and the other categories that aren't true "interaction types" (except "product of") if they become increasingly popular.

I think it is fair to equate gene with target. DGIdb is a source for searching drug gene interactions and potentially druggable genes. In this context the gene is, by reasonable definition, the target. Outside of the "product of" category, interactions from every other category (or at least, among the sampled interactions from my review of these catgories) fits the *drug affects gene target* interaction model, even if the interaction is indirect or the mechanism unknown. As you say, "product of" is a rare category that only confuses the issue of what an "interaction" is, and I think it should be dropped. I don't, however, want to drop any categories unless we all agree it should go.

I agree with you on keeping stimulator / suppressor. I was hesitant about it only because these categories are not widely-recognized drug action mechanisms (to my knowledge), and so I had to intuit what DrugBank intended by these labels. For example, I'm really not sure what separates "suppressor" from "inhibitor". It seems that the drugs in these examples perhaps suppress not only their target, but maybe differs by suppressing a broader physiological process (e.g. interacting with CYSLTR1 to suppress bronchial chemoattractant release, or promoting antineoplastic activity by competitively binding EGFR). This mirrors my findings in the "stimulator" category. These categories (that cumulatively account for 16 interactions in DGIdb) don't seem to be distinct from the existing categories of "inhibitor" or "inducer" which *are* well-defined pharmacological terms. That isn't by itself a good enough reason to drop them, but I thought it worth discussing.
