### ISSUE TITLE
Revise gene and drug claim views to appear more like gene and drug views

### ISSUE THREAD

**Issue by malachig** [griffithlab/dgi-db#88]
e.g.
http://dgidb.genome.wustl.edu/drug_claims/GuideToPharmacologyInteractions/4941
http://dgidb.genome.wustl.edu/gene_claims/GuideToPharmacologyInteractions/1797

**Comment by ahwagner** [comment]
This is going to be revised as part of @yanyangfeng's updates in #124

**Comment by yanyangfeng** [comment]
I think these are looking better on my dev instance. What do people think, can we close this issue?

<img width="1351" alt="screen shot 2017-05-05 at 4 07 15 pm" src="https://cloud.githubusercontent.com/assets/16638655/25764355/0201dce4-31ad-11e7-9a02-a1320383548a.png">
<img width="1344" alt="screen shot 2017-05-05 at 4 06 49 pm" src="https://cloud.githubusercontent.com/assets/16638655/25764358/034f7eee-31ad-11e7-8804-4ac3bce98202.png">

**Comment by ahwagner** [comment]
I think that we should refactor these views to look more like the new drug and gene group views. I'll revise the issue accordingly.

**Comment by yanyangfeng** [comment]
I believe this can be closed
