### ISSUE TITLE
Fix interaction claim type view

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#92]
On detailed results page, remove links from "interaction type" and make source links go to interaction claim.

On Summary results page, change checkboxes to interaction symbols that link to interaction claims.

**Comment by ahwagner** [comment]
this will be addressed as part of #149

**Comment by ahwagner** [comment]
#165 breaks links out to interaction claims from the detailed results view in interaction search results.

**Comment by ahwagner** [comment]
add 'n/a' as a default entry for interaction type on results display.

**Comment by yanyangfeng** [comment]
This should be fixed
