### ISSUE TITLE
Investigate out-of-memory issues and attempt to mitigate them

### ISSUE THREAD

**Issue by acoffman** [griffithlab/dgi-db#94]
Over the past weekend, systems detected several out-of-memory errors on DGIdb. These seemed to correspond to API requests involving a large number of genes. DGIdb has never been the most memory efficient application and I suspect the recent addition of a large amount of new data along with these large API requests pushed it over the edge.

There are some obvious mitigating steps we can take, and then probably some longer-term refactoring of the application we can do to improve its memory efficiency:
- Limit number of genes allowable per request. We can accomplish this in a variety of ways. The simplest is to put a hard limit on the number of Genes in a request and force users to split their lists into chunks. Another more involved solution would be accepting any size list but then paginating the result rather than performing the query all at once.
- Provide aggregate level data in API responses instead of detailed data. Currently our API responses contain almost all data we have for a given interaction. We could limit the multiple gene search endpoints to returning aggregate information and provide drill-down detail endpoints
- Update Ruby and Rails. Newer versions of Ruby have much more efficient garbage collection and newer versions of Rails have improved memory efficiency.

Longer term, if we anticipate that the data set will continue to grow, we will likely want to switch some of the core functionality to hand-tuned SQL queries rather than doing much of the logic in the ORM.

**Comment by bderickson** [comment]
Over the last week, we've seen 18 instances of the DGIdb host running out of memory and running oom-killer.
https://logstash-kibana.gsc.wustl.edu/#dashboard/temp/2JalarcmTRGFaLJvDGJCSg

So... bump! :)

**Comment by ahwagner** [comment]
perhaps this will resolve itself with #149.
