### ISSUE TITLE
Transition API results to drug primary names

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#95]
API results are still 1.0 style, returning the drug names used by the respective primary sources. Once the 2.0 web results (using drug group primary names) are streamlined, transition the API to match the web results.

**Comment by gspies** [comment]
After completing this issue, I found that some sources have multiple entries for a given gene/drug interaction claim. 

For example, when the query http://localhost:3000/api/v1/interactions.json?genes=FLT1,MM1,FAKE is made, these entries can be seen:
{
"interactionId": "078c9b85-cfd7-46a8-9dac-83298c1422ca",
"interactionType": "inhibitor",
"drugName": "AXITINIB",
"source": "MyCancerGenomeClinicalTrial"
},
{
"interactionId": "6aec202d-c926-4e72-9ce9-e042f23e0484",
"interactionType": "inhibitor",
"drugName": "AXITINIB",
"source": "MyCancerGenomeClinicalTrial"
},
{
"interactionId": "a0dedb22-698a-4f50-bb1b-9873500524d8",
"interactionType": "inhibitor",
"drugName": "AXITINIB",
"source": "MyCancerGenomeClinicalTrial"
},
{
"interactionId": "d6a394e4-a69f-434f-990d-528b7075fc9a",
"interactionType": "inhibitor",
"drugName": "AXITINIB",
"source": "MyCancerGenomeClinicalTrial"
}, 
...
{
"interactionId": "b46fd3f9-fa40-459f-934d-0843e8158d0b”,
"interactionType": "n/a”,
"drugName": "NINTEDANIB”,
"source": “ClearityFoundationClinicalTrial"
},
{
"interactionId": "7f366132-9b09-4fee-b800-27ea3ece90b7”,
“interactionType": "n/a”,
"drugName”: "NINTEDANIB”,
"source": “ClearityFoundationClinicalTrial"
},

These are just a few examples.

**Comment by ahwagner** [comment]
@gspies this is a great catch! We have known about #96 for a while, but haven't had the opportunity to address it. @malachig noted that this pertains to older, static resources that probably just need to be cleaned up on the backend, although a routine to dedup claims at import would be super nice! If you're up for it, maybe this would be a good issue to tackle next.

Also, I'll review your update later this week. It will be great to have consistent results!
