### ISSUE TITLE
Deduplicate interactions

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/dgi-db#96]
Multiple interaction records from the same source representing the same interaction should be merged at import.

**Comment by malachig** [comment]
Some static sources may need to just be cleaned up in the backend. For sources that are automatically updated, we just need to update the import logic to remove duplicate interactions.  In the future when we have interaction groups, this problem will in a sense go away.

**Comment by gspies** [comment]
I have written a script to eliminate all duplicate interactions in the database. I can push the change when I receive access to the database repo.

**Comment by acoffman** [comment]
@gspies I believe you should have access to the internal git repo now. I can help you push a new version of that submodule if you'd like! It may also make sense to post the script you used somewhere (maybe in a gist?) so that people can take a quick look at it.

**Comment by gspies** [comment]
Here is the script that I wrote: 
https://gist.github.com/gspies/8cdc2eec11b2de641d98934d8529f582

**Comment by ahwagner** [comment]
interaction groups are here, which should resolve the problem once #149 is completed. However, it would be worthwhile to check if duplicate interactions still exist in the database.

**Comment by susannasiebert** [comment]
When we move to the new-style importer, the logic being used there prevents creation of duplicate interactions, I will make a note to check on this again at that point.
