### ISSUE TITLE
Add DNA backdrop to header in dgi-db

### ISSUE THREAD

**Issue by malachig** [griffithlab/dgi-db#98]
Both CIViC and DoCM have this beautiful DNA image in the background:

<img width="1133" alt="screen shot 2016-01-20 at 4 30 03 pm" src="https://cloud.githubusercontent.com/assets/856728/12465326/173bf3e8-bf93-11e5-81bb-01067f4edb7a.png">

**Comment by ahwagner** [comment]
Argh. It seems like the appropriate place to put the header is [here](https://github.com/griffithlab/dgi-db/blob/issue_98/app/assets/stylesheets/main.css.less#L107-L108), but the changes do not show up in my dev instance. @jmcmichael / @acoffman, any thoughts on what might be interfering?
